FROM node:lts-hydrogen

WORKDIR /home/node/app
RUN mkdir /patches
RUN chown node:node -R /patches
COPY package.json /home/node/app/
RUN npm install
COPY server /home/node/app/server
COPY public /home/node/app/public
COPY src /home/node/app/src
COPY migrations /home/node/app/migrations
RUN ln -s /home/node/app/migrations /home/node/app/server/migrations
RUN chown node: -R /home/node/app
RUN npm run build

USER root